fix : Update ci-cd-pipeline.yml

diff --git a/.github/workflows/ci-cd-pipeline.yml b/.github/workflows/ci-cd-pipeline.yml
--- a/.github/workflows/ci-cd-pipeline.yml
+++ b/.github/workflows/ci-cd-pipeline.yml
@@ -61,3 +61,15 @@ jobs:
       - name: Deploy Docker container
         run: |
           docker run -d -p 8000:8000 pig:latest
+
+
+      # Verify if the Docker container is running
+      - name: Verify Container is Running
+        run: |
+          if [ -z "$(docker ps -q -f name=pig_app)" ]; then
+            echo "Deployment failed: Container is not running."
+            docker logs pig_app
+            exit 1
+          else
+            echo "Deployment successful: Container is running."
+          fi
